?start: query

query : match_clause | create_clause | delete_clause | update_clause

create_clause : "CREATE" path_pattern ("," path_pattern)*
match_clause  : "MATCH"  path_pattern ("WHERE" condition)? "RETURN" return_item ("," return_item)*
delete_clause : "DELETE" node_pattern ("WHERE" condition)?
update_clause : "UPDATE" node_pattern ("WHERE" condition)? "SET" set_item ("," set_item)*

path_pattern  : node_pattern (rel_pattern node_pattern)*
node_pattern  : "(" identifier (":" label)? (props)? ")"
rel_pattern   : "-[" rel_info "]->" | "<-[" rel_info "]-" | "-[" rel_info "]-"
rel_info      : identifier? (":" rel_type)? (props)?
rel_type      : CNAME

condition     : or_expr
or_expr       : and_expr ("OR" and_expr)*
and_expr      : primary_condition ("AND" primary_condition)*
primary_condition : NOT primary_condition | identifier "." prop_name op literal | "(" condition ")"  
op            : EQUAL | GT | GE | LT | LE | NE

return_item   : identifier ("." prop_name)?
set_item      : identifier "." prop_name "=" literal

NOT           : "NOT"
identifier    : CNAME
label         : CNAME
prop_name     : CNAME
props         : "{" prop_pair ("," prop_pair)* "}"
prop_pair     : CNAME ":" literal
literal       : STRING | NUMBER

EQUAL : "="
GT    : ">"
GE    : ">="
LT    : "<"
LE    : "<="
NE    : "!="

%import common.CNAME
%import common.ESCAPED_STRING -> STRING
%import common.NUMBER
%import common.WS
%ignore WS